export * from './assistant-page/assistant-page.component';
export * from './audio-to-text-page/audio-to-text-page.component';
export * from './img-generation-page/img-generation-page.component';
export * from './img-tunnibg-page/img-tunnibg-page.component';
export * from './orthography-page/orthography-page.component';
export * from './pros-cons-page/pros-cons-page.component';
export * from './pros-cons-stream-page/pros-cons-stream-page.component';
export * from './text-to-audios-page/text-to-audios-page.component';
export * from './translate-page/translate-page.component';
